apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-newdef-sept13 
  janus-idp.io/tekton: test-newdef-sept13
  backstage.io/kubernetes-id: test-newdef-sept13
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-newdef-sept13
resources: 
- application-dev.yaml